on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # weekly on Sunday
  workflow_dispatch:

jobs:
  scorecards:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.3.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          results_file: scorecards-results.json
          results_format: json
      - name: Upload Scorecard Results
        uses: actions/upload-artifact@v2
        with:
          name: scorecard-results
          path: scorecards-results.json
